######################################################################
# Automatically generated by qmake (2.01a) Thu Feb 5 22:42:17 2009
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += staticlib

# Input
HEADERS += QNamedPipe.h
SOURCES += QNamedPipe.cpp
